dist: trusty
sudo: false

language: python

python:
  - 3.6
  
virtualenv:
  system_site_packages: true

# command to install dependencies
before_script:
  - easy_install distribute
  - pip install --user -r requirements.txt

# command to run tests
script:
  - pytest

before_install:
  - if [[ $TOXENV = py35 && -f ~/virtualenv/python3.5/bin/activate ]]; then source ~/virtualenv/python3.5/bin/activate;
